[package]
name = "Amplityper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tidyvcf = "0.4.0"
scidataflow = "0.8.6"
